# Static code analysis for MATLAB/Octave files

name: MLint

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
        matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install miss_hit
      - name: Run code analysis
        run: |
          # Check the code with miss_hit
          mh_style.exe --octave 7.2